services:
  db1:
    container_name: db1
    image: mariadb:11.5.2
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: adminpass
      REPLICATION_PASSWORD: 'adminpass'
      GALERA: 'On'
      NODE_NAME: db1
      CLUSTER_NAME: journeyman
      CLUSTER_ADDRESS: gcomm://
      TZ: 'America/Miami'
    ports:
      - "3306:3306/tcp"
    volumes:
      - "./db1:/var/lib/mysql"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command:
      --wait_timeout=28800
      --character-set-server=utf8
      --collation-server=utf8_general_ci
      --max-allowed-packet=512M
      --net-buffer-length=5048576
      --wsrep-new-cluster
    stdin_open: true
    tty: true
    privileged: true
    ulimits:
      nofile:
        soft: 600000
        hard: 640000
  db2:
    container_name: db2
    image: mariadb:11.5.2
    restart: always
    links:
      - db1
    environment:
      MARIADB_ROOT_PASSWORD: adminpass
      REPLICATION_PASSWORD: 'adminpass'
      GALERA: 'On'
      NODE_NAME: db2
      CLUSTER_NAME: journeyman
      CLUSTER_ADDRESS: gcomm://db1
      TZ: 'America/Miami'
    ports:
      - "3307:3306/tcp"
    volumes:
      - "./db2:/var/lib/mysql"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command:
      --wait_timeout=28800
      --character-set-server=utf8
      --collation-server=utf8_general_ci
      --max-allowed-packet=512M
      --net-buffer-length=5048576
    stdin_open: true
    tty: true
    privileged: true
    depends_on:
      - db1
    ulimits:
      nofile:
        soft: 600000
        hard: 640000
  db3:
    container_name: db3
    image: mariadb:11.5.2
    restart: always
    links:
      - db1
    environment:
      MARIADB_ROOT_PASSWORD: adminpass
      REPLICATION_PASSWORD: 'adminpass'
      GALERA: 'On'
      NODE_NAME: db2
      CLUSTER_NAME: journeyman
      CLUSTER_ADDRESS: gcomm://db1
      TZ: 'America/Miami'
    ports:
      - "3308:3306/tcp"
    volumes:
      - "./db3:/var/lib/mysql"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command:
      --wait_timeout=28800
      --character-set-server=utf8
      --collation-server=utf8_general_ci
      --max-allowed-packet=512M
      --net-buffer-length=5048576
    stdin_open: true
    tty: true
    privileged: true
    depends_on:
      - db1
      - db2
  open-webui:
    build:
      context: .
      args:
        OLLAMA_BASE_URL: '/ollama'
      dockerfile: Dockerfile
    image: "ghcr.io/open-webui/open-webui:latest"
    container_name: "open-webui"
    volumes:
      - "open-webui:/app/backend/data"
    ports:
      - "3000:8080"
    environment:
      - 'OLLAMA_BASE_URL=http://host.docker.internal:11434'
      - 'WEBUI_SECRET_KEY='
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
  doris-fe:
    image: revhelix/doris.fe:2.0.15
    container_name: doris-fe
    ports:
      - "8030:8030" # Web UI
      - "9010:9010" # FE RPC
      - "9020:9020" # FE MySQL
    environment:
      - FE_PRIORITY_NETWORKS=127.0.0.1/8
      - FE_SERVERS=fe1:127.0.0.1:9010
      - FE_ID=1
    volumes:
      - ./doris/doris-meta:/doris-meta
      - ./doris/data/fe-01/doris-meta:/opt/apache-doris/fe/doris-meta
      - ./doris/data/fe-01/log:/opt/apache-doris/fe/log
    extra_hosts:
      - "host.docker.internal:host-gateway"
#  doris-be:
#    image: revhelix/doris.be:2.0.15
#    container_name: doris-be
#    ports:
#      - "9050:9050" # BE Heartbeat
#      - "9060:9060" # BE RPC
#      - "8040:8040" # BE Web UI
#    environment:
#      - BE_PRIORITY_NETWORKS=127.0.0.1/8
#    volumes:
#      - ./doris/doris-storage:/doris-storage
#      - ./doris/data/be/storage:/opt/apache-doris/be/storage
#      - ./doris/data/be/script:/docker-entrypoint-initdb.d
#      - ./doris/data/be/log:/opt/apache-doris/be/log
#    depends_on:
#      - doris-fe
#  doris-broker:
#    image: revhelix/doris.broker:2.0.15
#    container_name: doris-broker
#    ports:
#      - "8000:8000" # Broker Service

volumes:
  open-webui: {}
networks:
  doris_net:
    ipam:
      config:
        - subnet: 172.20.80.0/24