services:
  open-webui:
    network_mode: "host"
    build:
      context: .
      args:
        OLLAMA_BASE_URL: '/ollama'
      dockerfile: Dockerfile
    image: "ghcr.io/open-webui/open-webui:latest"
    container_name: "open-webui"
    volumes:
      - ./data/open-webui:/app/backend/data
    ports:
      - "3000:8080"
    environment:
      - 'OLLAMA_BASE_URL=http://host.docker.internal:11434'
      - 'WEBUI_SECRET_KEY='
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
  starrocks-fe-0:
    restart: unless-stopped
    image: starrocks/fe-ubuntu:latest
    hostname: starrocks-fe-0
    container_name: starrocks-fe-0
    command:
      - /bin/bash
      - -c
      - |
        /opt/starrocks/fe_entrypoint.sh starrocks-fe-0 starrocks-fe-1 starrocks-fe-2 starrocks-fe-3
    environment:
      - HOST_TYPE=FQDN
      - TZ=America/Toronto
    ports:
      - "1030:8030"
      - "2020:9020"
      - "3030:9030"
    volumes:
       - ./data/fe0_data:/opt/starrocks/fe/meta
  starrocks-fe-1:
    restart: unless-stopped
    image: starrocks/fe-ubuntu:latest
    hostname: starrocks-fe-1
    container_name: starrocks-fe-1
    command:
      - /bin/bash
      - -c
      - |
        /opt/starrocks/fe_entrypoint.sh starrocks-fe-0 starrocks-fe-1 starrocks-fe-2 starrocks-fe-3
    environment:
      - HOST_TYPE=FQDN
      - TZ=America/Toronto
    ports:
      - "1031:8030"
      - "2021:9020"
      - "3031:9030"
    volumes:
       - ./data/fe1_data:/opt/starrocks/fe/meta
  starrocks-fe-2:
    restart: unless-stopped
    image: starrocks/fe-ubuntu:latest
    hostname: starrocks-fe-2
    container_name: starrocks-fe-2
    command:
      - /bin/bash
      - -c
      - |
        /opt/starrocks/fe_entrypoint.sh starrocks-fe-0 starrocks-fe-1 starrocks-fe-2 starrocks-fe-3
    environment:
      - HOST_TYPE=FQDN
      - TZ=America/Toronto
    ports:
      - "1032:8030"
      - "2022:9020"
      - "3032:9030"
    volumes:
       - ./data/fe2_data:/opt/starrocks/fe/meta
  starrocks-fe-3:
    restart: unless-stopped
    image: starrocks/fe-ubuntu:latest
    hostname: starrocks-fe-3
    container_name: starrocks-fe-3
    command:
      - /bin/bash
      - -c
      - |
        /opt/starrocks/fe_entrypoint.sh starrocks-fe-0 starrocks-fe-1 starrocks-fe-2 starrocks-fe-3
    environment:
      - HOST_TYPE=FQDN
      - TZ=America/Toronto
    ports:
      - "1033:8030"
      - "2023:9020"
      - "3033:9030"
    volumes:
       - ./data/fe3_data:/opt/starrocks/fe/meta

  starrocks-be-0:
    restart: unless-stopped
    image: starrocks/be-ubuntu:latest
    hostname: starrocks-be-0
    container_name: starrocks-be-0
    command:
      - /bin/bash
      - -c
      - |
        /opt/starrocks/be_entrypoint.sh starrocks-fe-0 starrocks-fe-1 starrocks-fe-2 starrocks-fe-3
    environment:
      - HOST_TYPE=FQDN
      - TZ=America/Toronto
    depends_on:
      - starrocks-fe-0
      - starrocks-fe-1
    volumes:
      - ./data/be0_data:/opt/starrocks/be/storage
  starrocks-be-1:
    restart: unless-stopped
    image: starrocks/be-ubuntu:latest
    hostname: starrocks-be-1
    container_name: starrocks-be-1
    command:
      - /bin/bash
      - -c
      - |
        /opt/starrocks/be_entrypoint.sh starrocks-fe-0 starrocks-fe-1 starrocks-fe-2 starrocks-fe-3
    environment:
      - HOST_TYPE=FQDN
      - TZ=America/Toronto
    depends_on:
      - starrocks-fe-0
      - starrocks-fe-1
    volumes:
      - ./data/be1_data:/opt/starrocks/be/storage
  starrocks-be-2:
    restart: unless-stopped
    image: starrocks/be-ubuntu:latest
    hostname: starrocks-be-2
    container_name: starrocks-be-2
    command:
      - /bin/bash
      - -c
      - |
        /opt/starrocks/be_entrypoint.sh starrocks-fe-0 starrocks-fe-1 starrocks-fe-2 starrocks-fe-3
    environment:
      - HOST_TYPE=FQDN
      - TZ=America/Toronto
    depends_on:
      - starrocks-fe-0
      - starrocks-fe-1
    volumes:
      - ./data/be2_data:/opt/starrocks/be/storage
  starrocks-be-3:
    restart: unless-stopped
    image: starrocks/be-ubuntu:latest
    hostname: starrocks-be-3
    container_name: starrocks-be-3
    command:
      - /bin/bash
      - -c
      - |
        /opt/starrocks/be_entrypoint.sh starrocks-fe-0 starrocks-fe-1 starrocks-fe-2 starrocks-fe-3
    environment:
      - HOST_TYPE=FQDN
      - TZ=America/Toronto
    depends_on:
      - starrocks-fe-0
      - starrocks-fe-1
    volumes:
      - ./data/be3_data:/opt/starrocks/be/storage
  starrocks-be-4:
    restart: unless-stopped
    image: starrocks/be-ubuntu:latest
    hostname: starrocks-be-4
    container_name: starrocks-be-4
    command:
      - /bin/bash
      - -c
      - |
        /opt/starrocks/be_entrypoint.sh starrocks-fe-0 starrocks-fe-1 starrocks-fe-2 starrocks-fe-3
    environment:
      - HOST_TYPE=FQDN
      - TZ=America/Toronto
    depends_on:
      - starrocks-fe-0
      - starrocks-fe-1
    volumes:
      - ./data/be4_data:/opt/starrocks/be/storage
  starrocks-be-5:
    restart: unless-stopped
    image: starrocks/be-ubuntu:latest
    hostname: starrocks-be-5
    container_name: starrocks-be-5
    command:
      - /bin/bash
      - -c
      - |
        /opt/starrocks/be_entrypoint.sh starrocks-fe-0 starrocks-fe-1 starrocks-fe-2 starrocks-fe-3
    environment:
      - HOST_TYPE=FQDN
      - TZ=America/Toronto
    depends_on:
      - starrocks-fe-0
      - starrocks-fe-1
    volumes:
      - ./data/be5_data:/opt/starrocks/be/storage
  starrocks-be-6:
    restart: unless-stopped
    image: starrocks/be-ubuntu:latest
    hostname: starrocks-be-6
    container_name: starrocks-be-6
    command:
      - /bin/bash
      - -c
      - |
        /opt/starrocks/be_entrypoint.sh starrocks-fe-0 starrocks-fe-1 starrocks-fe-2 starrocks-fe-3
    environment:
      - HOST_TYPE=FQDN
      - TZ=America/Toronto
    depends_on:
      - starrocks-fe-0
      - starrocks-fe-1
    volumes:
      - ./data/be6_data:/opt/starrocks/be/storage
  starrocks-be-7:
    restart: unless-stopped
    image: starrocks/be-ubuntu:latest
    hostname: starrocks-be-7
    container_name: starrocks-be-7
    command:
      - /bin/bash
      - -c
      - |
        /opt/starrocks/be_entrypoint.sh starrocks-fe-0 starrocks-fe-1 starrocks-fe-2 starrocks-fe-3
    environment:
      - HOST_TYPE=FQDN
      - TZ=America/Toronto
    depends_on:
      - starrocks-fe-0
      - starrocks-fe-1
    volumes:
      - ./data/be7_data:/opt/starrocks/be/storage
  starrocks-be-8:
    restart: unless-stopped
    image: starrocks/be-ubuntu:latest
    hostname: starrocks-be-8
    container_name: starrocks-be-8
    command:
      - /bin/bash
      - -c
      - |
        /opt/starrocks/be_entrypoint.sh starrocks-fe-0 starrocks-fe-1 starrocks-fe-2 starrocks-fe-3
    environment:
      - HOST_TYPE=FQDN
      - TZ=America/Toronto
    depends_on:
      - starrocks-fe-0
      - starrocks-fe-1
    volumes:
      - ./data/be8_data:/opt/starrocks/be/storage
  starrocks-be-9:
    restart: unless-stopped
    image: starrocks/be-ubuntu:latest
    hostname: starrocks-be-9
    container_name: starrocks-be-9
    command:
      - /bin/bash
      - -c
      - |
        /opt/starrocks/be_entrypoint.sh starrocks-fe-0 starrocks-fe-1 starrocks-fe-2 starrocks-fe-3
    environment:
      - HOST_TYPE=FQDN
      - TZ=America/Toronto
    depends_on:
      - starrocks-fe-0
      - starrocks-fe-1
    volumes:
      - ./data/be9_data:/opt/starrocks/be/storage
  starrocks-be-10:
    restart: unless-stopped
    image: starrocks/be-ubuntu:latest
    hostname: starrocks-be-10
    container_name: starrocks-be-10
    command:
      - /bin/bash
      - -c
      - |
        /opt/starrocks/be_entrypoint.sh starrocks-fe-0 starrocks-fe-1 starrocks-fe-2 starrocks-fe-3
    environment:
      - HOST_TYPE=FQDN
      - TZ=America/Toronto
    depends_on:
      - starrocks-fe-0
      - starrocks-fe-1
    volumes:
      - ./data/be10_data:/opt/starrocks/be/storage
  starrocks-be-11:
    restart: unless-stopped
    image: starrocks/be-ubuntu:latest
    hostname: starrocks-be-11
    container_name: starrocks-be-11
    command:
      - /bin/bash
      - -c
      - |
        /opt/starrocks/be_entrypoint.sh starrocks-fe-0 starrocks-fe-1 starrocks-fe-2 starrocks-fe-3
    environment:
      - HOST_TYPE=FQDN
      - TZ=America/Toronto
    depends_on:
      - starrocks-fe-0
      - starrocks-fe-1
    volumes:
      - ./data/be11_data:/opt/starrocks/be/storage
volumes:
  open-webui: { }
  fe0_data: { }
  fe1_data: { }
  fe2_data: { }
  fe3_data: { }
  be0_data: { }
  be1_data: { }
  be2_data: { }
  be3_data: { }
  be4_data: { }
  be5_data: { }
  be6_data: { }
  be7_data: { }
  be8_data: { }
  be9_data: { }
  be10_data: { }
  be11_data: { }