services:
  open-webui:
    network_mode: "host"
    build:
      context: .
      args:
        OLLAMA_BASE_URL: '/ollama'
      dockerfile: Dockerfile
    image: "ghcr.io/open-webui/open-webui:latest"
    container_name: "open-webui"
    volumes:
      - ./data/open-webui:/app/backend/data
    environment:
      - 'OLLAMA_BASE_URL=http://host.docker.internal:11434'
      - 'WEBUI_SECRET_KEY='
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
  starrocks-fe-00:
    restart: unless-stopped
    image: starrocks/fe-ubuntu:latest
    hostname: starrocks-fe-00
    container_name: starrocks-fe-00
    command:
      - /bin/bash
      - -c
      - |
        ( cp -R  /overlay/fe/* / && HOST_TYPE=FQDN /opt/starrocks/fe_entrypoint.sh starrocks-fe-00 starrocks-fe-01 starrocks-fe-02 starrocks-fe-03 )
    environment:
      - HOST_TYPE=FQDN
      - TZ=America/Toronto
    ports:
      - "1030:8030"
      - "2020:9020"
      - "3030:9030"
    volumes:
       - ./data/starrocks/fe00_data:/opt/starrocks/fe/meta
       - ./starrocks:/overlay
  starrocks-fe-01:
    restart: unless-stopped
    image: starrocks/fe-ubuntu:latest
    hostname: starrocks-fe-01
    container_name: starrocks-fe-01
    command:
      - /bin/bash
      - -c
      - |
        ( cp -R  /overlay/fe/* / && HOST_TYPE=FQDN /opt/starrocks/fe_entrypoint.sh starrocks-fe-00 starrocks-fe-01 starrocks-fe-02 starrocks-fe-03 )
    environment:
      - HOST_TYPE=FQDN
      - TZ=America/Toronto
    ports:
      - "1031:8030"
      - "2021:9020"
      - "3031:9030"
    volumes:
       - ./data/starrocks/fe01_data:/opt/starrocks/fe/meta
       - ./starrocks:/overlay
  starrocks-fe-02:
    restart: unless-stopped
    image: starrocks/fe-ubuntu:latest
    hostname: starrocks-fe-02
    container_name: starrocks-fe-02
    command:
      - /bin/bash
      - -c
      - |
        ( cp -R  /overlay/fe/* / && HOST_TYPE=FQDN /opt/starrocks/fe_entrypoint.sh starrocks-fe-00 starrocks-fe-01 starrocks-fe-02 starrocks-fe-03 )
    environment:
      - HOST_TYPE=FQDN
      - TZ=America/Toronto
    ports:
      - "1032:8030"
      - "2022:9020"
      - "3032:9030"
    volumes:
       - ./data/starrocks/fe02_data:/opt/starrocks/fe/meta
       - ./starrocks:/overlay
  starrocks-fe-03:
    restart: unless-stopped
    image: starrocks/fe-ubuntu:latest
    hostname: starrocks-fe-03
    container_name: starrocks-fe-03
    command:
      - /bin/bash
      - -c
      - |
        ( cp -R  /overlay/fe/* / && HOST_TYPE=FQDN /opt/starrocks/fe_entrypoint.sh starrocks-fe-00 starrocks-fe-01 starrocks-fe-02 starrocks-fe-03 )
    environment:
      - HOST_TYPE=FQDN
      - TZ=America/Toronto
    ports:
      - "1033:8030"
      - "2023:9020"
      - "3033:9030"
    volumes:
       - ./data/starrocks/fe03_data:/opt/starrocks/fe/meta
       - ./starrocks:/overlay
  starrocks-be-00:
    restart: unless-stopped
    image: starrocks/be-ubuntu:latest
    hostname: starrocks-be-00
    container_name: starrocks-be-00
    command:
      - /bin/bash
      - -c
      - |
        ( cp -R  /overlay/be/* / && /opt/starrocks/be_entrypoint.sh  starrocks-fe-00 starrocks-fe-01 starrocks-fe-02 starrocks-fe-03 )
    environment:
      - HOST_TYPE=FQDN
      - TZ=America/Toronto
    depends_on:
      - starrocks-fe-00
      - starrocks-fe-01
    volumes:
      - ./data/starrocks/be00_data:/opt/starrocks/be/storage
      - ./starrocks:/overlay
  starrocks-be-01:
    restart: unless-stopped
    image: starrocks/be-ubuntu:latest
    hostname: starrocks-be-01
    container_name: starrocks-be-01
    command:
      - /bin/bash
      - -c
      - |
        ( cp -R  /overlay/be/* / && /opt/starrocks/be_entrypoint.sh  starrocks-fe-00 starrocks-fe-01 starrocks-fe-02 starrocks-fe-03 )
    environment:
      - HOST_TYPE=FQDN
      - TZ=America/Toronto
    depends_on:
      - starrocks-fe-00
      - starrocks-fe-01
      - starrocks-fe-02
      - starrocks-fe-03
    volumes:
      - ./data/starrocks/be01_data:/opt/starrocks/be/storage
      - ./starrocks:/overlay
  starrocks-be-02:
    restart: unless-stopped
    image: starrocks/be-ubuntu:latest
    hostname: starrocks-be-02
    container_name: starrocks-be-02
    command:
      - /bin/bash
      - -c
      - |
        ( cp -R  /overlay/be/* / && /opt/starrocks/be_entrypoint.sh  starrocks-fe-00 starrocks-fe-01 starrocks-fe-02 starrocks-fe-03 )
    environment:
      - HOST_TYPE=FQDN
      - TZ=America/Toronto
    depends_on:
      - starrocks-fe-00
      - starrocks-fe-01
      - starrocks-fe-02
      - starrocks-fe-03
    volumes:
      - ./data/starrocks/be02_data:/opt/starrocks/be/storage
      - ./starrocks:/overlay
  starrocks-be-03:
    restart: unless-stopped
    image: starrocks/be-ubuntu:latest
    hostname: starrocks-be-03
    container_name: starrocks-be-03
    command:
      - /bin/bash
      - -c
      - |
        ( cp -R  /overlay/be/* / && /opt/starrocks/be_entrypoint.sh  starrocks-fe-00 starrocks-fe-01 starrocks-fe-02 starrocks-fe-03 )
    environment:
      - HOST_TYPE=FQDN
      - TZ=America/Toronto
    depends_on:
      - starrocks-fe-00
      - starrocks-fe-01
      - starrocks-fe-02
      - starrocks-fe-03
    volumes:
      - ./data/starrocks/be03_data:/opt/starrocks/be/storage
      - ./starrocks:/overlay
  starrocks-be-04:
    restart: unless-stopped
    image: starrocks/be-ubuntu:latest
    hostname: starrocks-be-04
    container_name: starrocks-be-04
    command:
      - /bin/bash
      - -c
      - |
        ( cp -R  /overlay/be/* / && /opt/starrocks/be_entrypoint.sh  starrocks-fe-00 starrocks-fe-01 starrocks-fe-02 starrocks-fe-03 )
    environment:
      - HOST_TYPE=FQDN
      - TZ=America/Toronto
    depends_on:
      - starrocks-fe-00
      - starrocks-fe-01
      - starrocks-fe-02
      - starrocks-fe-03
    volumes:
      - ./data/starrocks/be04_data:/opt/starrocks/be/storage
      - ./starrocks:/overlay
  starrocks-be-05:
    restart: unless-stopped
    image: starrocks/be-ubuntu:latest
    hostname: starrocks-be-05
    container_name: starrocks-be-05
    command:
      - /bin/bash
      - -c
      - |
        ( cp -R  /overlay/be/* / && /opt/starrocks/be_entrypoint.sh  starrocks-fe-00 starrocks-fe-01 starrocks-fe-02 starrocks-fe-03 )
    environment:
      - HOST_TYPE=FQDN
      - TZ=America/Toronto
    depends_on:
      - starrocks-fe-00
      - starrocks-fe-01
      - starrocks-fe-02
      - starrocks-fe-03
    volumes:
      - ./data/starrocks/be05_data:/opt/starrocks/be/storage
      - ./starrocks:/overlay
  starrocks-be-06:
    restart: unless-stopped
    image: starrocks/be-ubuntu:latest
    hostname: starrocks-be-06
    container_name: starrocks-be-06
    command:
      - /bin/bash
      - -c
      - |
        ( cp -R  /overlay/be/* / && /opt/starrocks/be_entrypoint.sh  starrocks-fe-00 starrocks-fe-01 starrocks-fe-02 starrocks-fe-03 )
    environment:
      - HOST_TYPE=FQDN
      - TZ=America/Toronto
    depends_on:
      - starrocks-fe-00
      - starrocks-fe-01
      - starrocks-fe-02
      - starrocks-fe-03
    volumes:
      - ./data/starrocks/be06_data:/opt/starrocks/be/storage
      - ./starrocks:/overlay
  starrocks-be-07:
    restart: unless-stopped
    image: starrocks/be-ubuntu:latest
    hostname: starrocks-be-07
    container_name: starrocks-be-07
    command:
      - /bin/bash
      - -c
      - |
        ( cp -R  /overlay/be/* / && /opt/starrocks/be_entrypoint.sh  starrocks-fe-00 starrocks-fe-01 starrocks-fe-02 starrocks-fe-03 )
    environment:
      - HOST_TYPE=FQDN
      - TZ=America/Toronto
    depends_on:
      - starrocks-fe-00
      - starrocks-fe-01
      - starrocks-fe-02
      - starrocks-fe-03
    volumes:
      - ./data/starrocks/be07_data:/opt/starrocks/be/storage
      - ./starrocks:/overlay
  starrocks-be-08:
    restart: unless-stopped
    image: starrocks/be-ubuntu:latest
    hostname: starrocks-be-08
    container_name: starrocks-be-08
    command:
      - /bin/bash
      - -c
      - |
        ( cp -R  /overlay/be/* / && /opt/starrocks/be_entrypoint.sh  starrocks-fe-00 starrocks-fe-01 starrocks-fe-02 starrocks-fe-03 )
    environment:
      - HOST_TYPE=FQDN
      - TZ=America/Toronto
    depends_on:
      - starrocks-fe-00
      - starrocks-fe-01
      - starrocks-fe-02
      - starrocks-fe-03
    volumes:
      - ./data/starrocks/be08_data:/opt/starrocks/be/storage
      - ./starrocks:/overlay
  starrocks-be-09:
    restart: unless-stopped
    image: starrocks/be-ubuntu:latest
    hostname: starrocks-be-09
    container_name: starrocks-be-09
    command:
      - /bin/bash
      - -c
      - |
        ( cp -R  /overlay/be/* / && /opt/starrocks/be_entrypoint.sh  starrocks-fe-00 starrocks-fe-01 starrocks-fe-02 starrocks-fe-03 )
    environment:
      - HOST_TYPE=FQDN
      - TZ=America/Toronto
    depends_on:
      - starrocks-fe-00
      - starrocks-fe-01
      - starrocks-fe-02
      - starrocks-fe-03
    volumes:
      - ./data/starrocks/be09_data:/opt/starrocks/be/storage
      - ./starrocks:/overlay
  starrocks-be-10:
    restart: unless-stopped
    image: starrocks/be-ubuntu:latest
    hostname: starrocks-be-10
    container_name: starrocks-be-10
    command:
      - /bin/bash
      - -c
      - |
        ( cp -R  /overlay/be/* / && /opt/starrocks/be_entrypoint.sh  starrocks-fe-00 starrocks-fe-01 starrocks-fe-02 starrocks-fe-03 )
    environment:
      - HOST_TYPE=FQDN
      - TZ=America/Toronto
    depends_on:
      - starrocks-fe-00
      - starrocks-fe-01
      - starrocks-fe-02
      - starrocks-fe-03
    volumes:
      - ./data/starrocks/be10_data:/opt/starrocks/be/storage
      - ./starrocks:/overlay
  starrocks-be-11:
    restart: unless-stopped
    image: starrocks/be-ubuntu:latest
    hostname: starrocks-be-11
    container_name: starrocks-be-11
    command:
      - /bin/bash
      - -c
      - |
        ( cp -R  /overlay/be/* / && /opt/starrocks/be_entrypoint.sh  starrocks-fe-00 starrocks-fe-01 starrocks-fe-02 starrocks-fe-03 )
    environment:
      - HOST_TYPE=FQDN
      - TZ=America/Toronto
    depends_on:
      - starrocks-fe-00
      - starrocks-fe-01
      - starrocks-fe-02
      - starrocks-fe-03
    volumes:
      - ./data/starrocks/be11_data:/opt/starrocks/be/storage
      - ./starrocks:/overlay